### ISSUE TITLE
Add ScreenEat to AUR

### ISSUE THREAD

**Issue by thenav56** [NISH1001/ScreenEat#12]

**Comment by NISH1001** [comment]
First, we have to make sure the gtk dependencies are consistent over various sytems.

**Comment by NISH1001** [comment]
@thenav56 
Can you test the from the testpypi version.

https://test.pypi.org/project/ScreenEat/

And let know of any issue regarding pip installation.

**Comment by thenav56** [comment]
@NISH1001, pip install worked seamlessly.

![image](https://user-images.githubusercontent.com/7059255/44011204-f14cd97e-9ed6-11e8-90f5-4efcacde2d5c.png)
