### ISSUE TITLE
Cannot install with pip3

### ISSUE THREAD

**Issue by igaurab** [NISH1001/ScreenEat#21]
```raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/screen-eat/
```

**Comment by NISH1001** [comment]
Can you try with `setup.py`? It's been a long time I haven't updated this repository.

**Comment by NISH1001** [comment]
@igaurab I just tried using `setup.py`. It's working fine for me.

**Comment by igaurab** [comment]
Yes dai, it works, I installed it with setup.py thereafter.

**Comment by igaurab** [comment]
For reference: 
`
pip3 install git+https://github.com/NISH1001/ScreenEat.git`

**Comment by NISH1001** [comment]
@igaurab You can send a PR if any. :)
