### ISSUE TITLE
Issue With Wayland

### ISSUE THREAD

**Issue by NISH1001** [NISH1001/ScreenEat#25]
@tnagorra is there any way we can get screenshot in wayland mode? It seems we don't quite get actie window.
(Recently switched to wayland and ScreenEat doesn't work).

**Comment by tnagorra** [comment]
Yes, it's a well known issue. I don't think Gdk has the same api for wayland

**Comment by NISH1001** [comment]
Had "checked" a few things related to this issue. Shall update over the weekends...
