### ISSUE TITLE
Transparency issue on ;; Ctrl+Super+I 

### ISSUE THREAD

**Issue by codeezer** [NISH1001/ScreenEat#3]
After the update of ubuntu lts version , while cropping screenshot the screen isnt transparent its totally opaque . Please , Fix this :) 
Device : Ubuntu 16.04 LTS
GTK version : 13

**Comment by NISH1001** [comment]
This issue has been solved now. We have decided to not use transparent window. Instead we fixed the issue by faking the whole desktop and rendering it on another window onto which cropping is done.
