### ISSUE TITLE
Doesn't work good in multi screen situation

### ISSUE THREAD

**Issue by frozenhelium** [NISH1001/ScreenEat#6]
Here is a sample snap
![image](https://cloud.githubusercontent.com/assets/4931541/17200637/cc932074-54a6-11e6-9708-b2cec3aa4511.png)

**Comment by tnagorra** [comment]
Bug becomes a feature. Now you can screenshot more than one screen at a time.
:stuck_out_tongue:

**Comment by frozenhelium** [comment]
not exactly, you cannot crop it because the image is not scaled to fit either screen
